name: Assign Issues

on:
  issues:
    types:
      - opened

jobs:
  assign-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Issue Template
        id: issue_template
        run: |

          issue_template=$(cat $GITHUB_EVENT_PATH | jq -r '.issue.body' | grep -oP '(?<=name: ).*(?=\s*title:)')

          echo "::set-output name=issue_template::$issue_template"
        shell: bash

      - name: Assign Issue
        if: steps.issue_template.outputs.issue_template
        run: |

          issue_template=${{ steps.issue_template.output.issue_template }}
          assignees=$(cat .github/ISSUE_TEMPLATE/${issue_template}.md | grep -oP '(?<=assignees:\s*- ).*')

          issue_number=$(cat $GITHUB_EVENT_PATH | jq -r '.issue.number')
          for assignee in $assignees; do
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"assignees\":[\"$assignee\"]}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/assignees"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
              
